# This workflow checks the diff between base branch and PR

name: Check Diffs

on: [ pull_request ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch parent
      uses: actions/checkout@v2
      with:
        ${GITHUB_BASE_REF}
    - name: Checkout repo current
      uses: actions/checkout@v2
    - name: Get changes from commits
      run: |
        printenv 
        echo 'xxxxxxxxxxx'
        pwd
        echo 'xxxxxxxxxxx'
        ls -a
        echo 'xxxxxxxxxxx'
        git diff ${GITHUB_BASE_REF}...
