# This workflow checks the diff between base branch and PR

# https://github.com/actions/checkout
#
name: Check Diffs

on: [ pull_request ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo current
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changes from commits
      run: |
        printenv 
        echo 'xxxxxxxxxxx'
        /usr/bin/git status
        echo 'xxxxxxxxxxx'
        /usr/bin/git diff 
        echo 'xxxxxxxxxxx'
        /usr/bin/git branch -va
        echo 'xxxxxxxxxxx'
        echo git diff 542125a...
        /usr/bin/git diff 542125a...
        echo 'xxxxxxxxxxx'
        echo git diff ${GITHUB_BASE_REF}...
        /usr/bin/git diff ${GITHUB_BASE_REF}...
        echo 'xxxxxxxxxxx'
