# This workflow checks the diff between base branch and PR

name: Check Diffs

on: [ pull_request ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: |
        printenv 
        echo 'xxxxxxxxxxx'
        ls -a
        echo 'xxxxxxxxxxx'
        ls -a ..
        echo 'xxxxxxxxxxx'
        #git diff ${GITHUB_BASE_REF}...
