# This workflow checks the diff between base branch and PR

# https://github.com/actions/checkout
#
name: Check Diffs

on: [ pull_request ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo current
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changes from commits
      run: |
        printenv
        /usr/bin/git diff remotes/origin/${GITHUB_BASE_REF}...
